### ISSUE TITLE
support for opening file in editor using ```v``` key

### ISSUE THREAD

**Issue by chrisbeardy** [ttscoff/mdless#53]
Not sure if a bug or a non implemented feature.

When using less you can open the file in the default text editor by pressing the ```v``` button. and on exit of the text editing it returns to less.

It would be great to add this to mdless for quick editing of files. 

Currently I am getting the error message ```Cannot edit standard input (press RETURN)```
![image](https://user-images.githubusercontent.com/20585410/85139215-03d08300-b23c-11ea-9603-1521ffece4f4.png)

When pressing the ```v``` key.

**Comment by ttscoff** [comment]
This is because it's passing the rendered output to less (or your 
configured pager) via STDIN, not writing an editable file to disk. Once 
it's passed to the pager, I can't intercept keystrokes anymore, so it's 
not feasible to implement coding writing my own pager, and I'd rather 
not do that.

-Brett

**Comment by chrisbeardy** [comment]
I see, this makes sense, I just read the code now and can see now that it's just piping to the pager and not actually rending the text itself. Should have had a look before. Nevermind. Nice little program though!
