### ISSUE TITLE
Images in text using chafa

### ISSUE THREAD

**Issue by hhoeflin** [ttscoff/mdless#62]
Not a bug, more a feature request or an idea. There is the excellent image rendering program called 'chafa' that converts images to text representations. It works pretty well for me in the default settings. This could be used if installed to render images more terminal independent (albeit at worse quality) than the iterm option does.

**Comment by ttscoff** [comment]
I'll check this out!

**Comment by ttscoff** [comment]
This turned out to be a great idea. Version 1.0.17 is out now and prioritizes chafa if it's available over imgcat. Works with pagers and everything, very nice.

I have it downloading remote images to a temp directory, processing with chafa, then cleaning up after itself, so it works with both local and remote images (only tested on a few).
